build: off
clone_depth: 5
platform: x64
configuration: Release

environment:
    PKG_NAME: limix_plot
    PYTHON: "C:\\Python36-x64"

build_script:
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/horta/ci/master/appveyor.bat', 'appveyor.bat')" && appveyor.bat
